execute pathogen#infect()
syntax on
filetype plugin indent on

" Set tab handling
set expandtab
set shiftwidth=4
set tabstop=4
set autoindent
set cindent
set ignorecase
set smartcase
set nowrap

" Show incomplete commands in status bar.
set showcmd

" Show cursor line by default
set cursorline

" Always show a status line
set laststatus=2

" line numbers on
set number

" next/previous search results always centered
nmap n nzz
nmap s-n s-nzz
nnoremap n nzz
nnoremap N Nzz
nnoremap * *zz
nnoremap # #zz
nnoremap g* g*zz
nnoremap g# g#zz

" incremental search
set incsearch
set hlsearch
let mapleader="\\"
map <Leader>h :set hls!<CR>
map <Leader>i :set ignorecase!<CR>
map <Leader>l :set number!<CR>
map <Leader>p :set paste!<CR>
map <Leader>c :set cursorline!<CR>
map <C-n> :NERDTreeToggle<CR>
map <C-h> <C-w><C-h>
map <C-j> <C-w><C-j>
map <C-k> <C-w><C-k>
map <C-l> <C-w><C-l>

" one space after a period not two
set nojoinspaces

set lazyredraw

" disable literal tabs
highlight LiteralTabs ctermbg=darkgreen guibg=darkgreen
match LiteralTabs /\s\ /

" highlight extra spaces
highlight ExtraWhitespace ctermbg=darkgreen guibg=darkgreen
match ExtraWhitespace /\s\+\%#\@<!$/
autocmd InsertLeave * redraw!
highlight VisualNOS ctermbg=236
highlight Visual ctermbg=236
highlight CursorLine ctermbg=236
